(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Info-mode-hook (quote (turn-on-font-lock)))
 '(auto-save-list-file-prefix "~/.emacs.d/asave/.saves-")
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backup/"))))
 '(c-require-final-newline (quote ((c-mode . t) (c++-mode . t) (objc-mode . t) (java-mode . t))))
 '(custom-file "~/.emacs.d/custom.el")
 '(debug-on-error t)
 '(diary-file "~/.emacs.d/diary")
 '(display-time-day-and-date t)
 '(display-time-default-load-average nil)
 '(display-time-mail-face nil)
 '(display-time-mode t)
 '(display-time-world-list (quote (("DST5EDT" "Boston") ("DST8PDT" "San Francisco") ("GMT0BST" "Belfast") ("JST-9" "Tokyo"))))
 '(emacs-lisp-mode-hook (quote (turn-on-eldoc-mode imenu-add-menubar-index checkdoc-minor-mode)))
 '(eshell-directory-name "~/.emacs.d/.eshell/")
 '(even-window-heights nil)
 '(find-function-source-path (cons "/emacs-23.1/src/" load-path))
 '(focus-follows-mouse t)
 '(fortune-always-compile nil)
 '(fortune-dir "~/.emacs.d/")
 '(fortune-file "~/.emacs.d/fortunes")
 '(fringe-mode (quote (nil . 0)) nil (fringe))
 '(global-hl-line-mode t)
 '(help-mode-hook (quote (variable-pitch-mode)))
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-buffer-choice t)
 '(initial-major-mode (quote emacs-lisp-mode))
 '(initial-scratch-message "")
 '(lisp-indent-function (quote common-lisp-indent-function))
 '(mailclient-place-body-on-clipboard-flag nil)
 '(mode-require-final-newline (quote visit-save))
 '(mouse-avoidance-mode (quote animate) nil (avoid))
 '(nroff-mode-hook (quote (variable-pitch-mode)))
 '(ns-tool-bar-display-mode nil t)
 '(recentf-max-saved-items 30)
 '(recentf-mode t)
 '(recentf-save-file "~/.emacs.d/.recentf")
 '(require-final-newline (quote visit-save))
 '(save-place t nil (saveplace))
 '(save-place-file "~/.emacs.d/.emacs-places")
 '(scroll-bar-mode nil)
 '(server-host nil)
 '(server-mode nil)
 '(server-name "emacsserver")
 '(server-window (quote switch-to-buffer-other-frame))
 '(show-paren-style (quote expression))
 '(size-indication-mode t)
 '(slime-complete-symbol-function (quote slime-fuzzy-complete-symbol))
 '(slime-repl-history-file "~/.emacs.d/slime-history.eld")
 '(snake-initial-velocity-x 1 t)
 '(snake-randomize-apples nil)
 '(speedbar-show-unknown-files t)
 '(tab-width 4)
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(toe-highscore-file "~/.emacs.d/toe-scores")
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(user-full-name "Stuart Hacking")
 '(visible-bell t)
 '(visual-line-mode nil t)
 '(yow-file "~/.emacs.d/yow.lines"))

(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "Black" :foreground "gray95" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 106 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background dark)) (:foreground "LightSalmon" :weight extra-bold))))
 '(hl-line ((t (:background "gray5")))))
