(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Info-mode-hook (quote (turn-on-font-lock)))
 '(auto-save-list-file-prefix "~/.emacs.d/asave/.saves-")
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backup/"))))
 '(c-default-style (quote ((c-mode . "Stroustrup") (c++-mode . "Stroustrup") (java-mode . "Java") (awk-mode . "AWK"))))
 '(c-require-final-newline (quote ((c-mode . t) (c++-mode . t) (objc-mode . t) (java-mode . t))))
 '(column-number-mode t)
 '(custom-enabled-themes (quote (wombat)))
 '(custom-file "~/.emacs.d/custom.el")
 '(custom-safe-themes (quote ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" default)))
 '(debug-on-error t)
 '(diary-file "~/.emacs.d/diary")
 '(display-time-day-and-date nil)
 '(display-time-default-load-average nil)
 '(display-time-mail-face nil)
 '(display-time-world-list (quote (("DST5EDT" "Boston") ("DST8PDT" "San Francisco") ("GMT0BST" "Belfast") ("JST-9" "Tokyo"))))
 '(eshell-directory-name "~/.emacs.d/.eshell/")
 '(even-window-heights nil)
 '(fci-rule-color "#073642")
 '(focus-follows-mouse t)
 '(foreground-color "#657b83")
 '(fortune-always-compile nil)
 '(fortune-dir "~/.emacs.d/")
 '(fortune-file "~/.emacs.d/fortunes")
 '(fringe-mode (quote (nil . 0)) nil (fringe))
 '(global-hl-line-mode nil)
 '(haskell-mode-hook (quote (turn-on-haskell-indentation turn-on-haskell-doc-mode)) t)
 '(haskell-stylish-on-save t)
 '(help-mode-hook (quote (variable-pitch-mode)))
 '(highlight-changes-colors (quote ("#d33682" "#6c71c4")))
 '(highlight-tail-colors (quote (("#073642" . 0) ("#546E00" . 20) ("#00736F" . 30) ("#00629D" . 50) ("#7B6000" . 60) ("#8B2C02" . 70) ("#93115C" . 85) ("#073642" . 100))))
 '(hippie-expand-try-functions-list (quote (try-complete-lisp-symbol try-complete-lisp-symbol-partially try-expand-all-abbrevs try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-expand-line try-complete-file-name-partially try-complete-file-name)))
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-major-mode (quote emacs-lisp-mode))
 '(initial-scratch-message "")
 '(mailclient-place-body-on-clipboard-flag nil)
 '(minibuffer-auto-raise t)
 '(mode-require-final-newline (quote visit-save))
 '(mouse-avoidance-mode (quote animate) nil (avoid))
 '(nroff-mode-hook (quote (variable-pitch-mode)))
 '(ns-tool-bar-display-mode nil t)
 '(org-agenda-files (concat user-emacs-directory ".org-agenda-files"))
 '(org-babel-load-languages (quote ((emacs-lisp . t))))
 '(org-src-tab-acts-natively t)
 '(recentf-max-saved-items 30)
 '(recentf-mode t)
 '(recentf-save-file (concat user-emacs-directory ".recentf"))
 '(require-final-newline (quote visit-save))
 '(save-place t nil (saveplace))
 '(save-place-file (concat user-emacs-directory ".emacs-places"))
 '(scroll-bar-mode nil)
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(size-indication-mode t)
 '(speedbar-show-unknown-files t)
 '(tab-width 4)
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(toe-highscore-file (concat user-emacs-directory "toe-scores"))
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(user-full-name "Stuart Hacking")
 '(vc-annotate-background "#93a1a1")
 '(vc-annotate-color-map (quote ((20 . "#990A1B") (40 . "#FF6E64") (60 . "#cb4b16") (80 . "#7B6000") (100 . "#b58900") (120 . "#DEB542") (140 . "#546E00") (160 . "#859900") (180 . "#B4C342") (200 . "#3F4D91") (220 . "#6c71c4") (240 . "#9EA0E5") (260 . "#2aa198") (280 . "#69CABF") (300 . "#00629D") (320 . "#268bd2") (340 . "#69B7F0") (360 . "#d33682"))))
 '(vc-annotate-very-old-color "#93115C")
 '(visible-bell t)
 '(visual-line-mode nil t)
 '(yow-file (concat user-emacs-directory "yow.lines")))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(font-lock-string-face ((t (:foreground "#2aa198" :weight bold))))
 '(org-block-background ((t (:background "Black"))))
 '(org-block-begin-line ((t (:inherit org-meta-line :background "grey80" :foreground "orangered" :box (:line-width 2 :color "grey75" :style released-button)))) t)
 '(org-block-end-line ((t (:inherit org-block-begin-line))) t))

